name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
    
env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: 'superuser'
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v4
          with:
            node-version: 20
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result
            path: test-results.xml

    code-coverage:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4.2.2

        - name: Setup Node.js environment
          uses: actions/setup-node@v3.9.1
          with:
            node-version: 18

        - name: Install NodeJS dependencies
          run: npm install

        - name: Run Code-coverage command
          run: npm run code-coverage

        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v4.6.2
          with:
            name: Code-Coverage-Result
            path: coverage
            retenion-days: 5


    dev-deploy:
        runs-on: ubuntu-latest
        needs: docker
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: install kubectl
          uses: azure/setup-kubectl@v4
          with:
            version: 'v1.28.1'
          id: kube-install
        
        - name: set context
          uses: azure/k8s-set-context@v4
          with:
            method: kubeconfig
            kubeconfig: ${{ secrets.KUBECONFIG }}

        - name: kube command
          run: kubectl version -o yaml